### ISSUE TITLE
org.springframework.security.access.AccessDeniedException: Access is denied (probably roles are not parsed properly)

### ISSUE THREAD

**Issue by DanailMinchev** [auth0-samples/auth0-spring-security-api-sample#1]
Hi @arcseldon ,

I have tried the example and the authentication is working only for `http://localhost:3001/secured/ping` endpoint.

The endpoints:
- `http://localhost:3001/secured/username`
- `http://localhost:3001/secured/post`

throw `org.springframework.security.access.AccessDeniedException: Access is denied` exception and in the response (example):
`{"timestamp":1465930478547,"status":403,"error":"Forbidden","message":"Access is denied","path":"/secured/username"}`

What I did is: I changed `com.auth0.example.SecuredPingController#securedPing` method and added `Principal principal` parameter to see if my JWT has been generated fine and is accepted.
Please find attached screenshot and see the contents of the `principal` object:
![principal-debug](https://cloud.githubusercontent.com/assets/7883702/16055768/75d319dc-326a-11e6-827c-fce3511c9778.png)

I think the problem is in authorization part - probably the roles are not parsed.

Details on configuration and steps to reproduce:

1). I have generated JWT using this request:

```
curl -X POST -H "Content-Type: application/json" -d '{"client_id": "client_id_here", "username": "user@example.com", "password": "password_here", "connection": "Username-Password-Authentication", "grant_type": "password", "scope": "openid offline_access", "device": "DeviceTest1"}' https://username.eu.auth0.com/oauth/ro
```

2). Tested `http://localhost:3001/ping` - OK

```
curl -X GET -H "Content-Type: application/json" -H "Cache-Control: no-cache" "http://localhost:3001/ping"
```

Result:

```
All good. You don't need to be authenticated to call this
```

3). Tested `http://localhost:3001/secured/ping` - OK

```
curl -X GET -H "Authorization: Bearer ID_TOKEN_FROM_POINT_1" -H "Content-Type: application/json" -H "Cache-Control: no-cache" "http://localhost:3001/secured/ping"
```

Result:

```
All good. You only get this message if you're authenticated
```

4). Tested `http://localhost:3001/secured/username` - **ERROR**

```
curl -X GET -H "Authorization: Bearer ID_TOKEN_FROM_POINT_1" -H "Content-Type: application/json" -H "Cache-Control: no-cache" "http://localhost:3001/secured/username"
```

Result:

```
{"timestamp":1465931176377,"status":403,"error":"Forbidden","message":"Access is denied","path":"/secured/username"}
```

---

Auth0 Dashboard screenshots:

The user's Metadata screenshot:
![user details - metadata](https://cloud.githubusercontent.com/assets/7883702/16056101/e9f1e37e-326b-11e6-83f2-1bd03923d7a7.png)

The rules:
![rules - index](https://cloud.githubusercontent.com/assets/7883702/16056164/2d08ab5c-326c-11e6-8e4c-1890bae90508.png)
![rules - edit](https://cloud.githubusercontent.com/assets/7883702/16056169/31e2b1ea-326c-11e6-8e7f-4570022b8a82.png)

**Comment by arcseldon** [comment]
@DanailMinchev - Hello again!  Thanks for the early feedback. I have fully updated the Sample. Please can you do a fresh `git pull` - and you will find full instructions in the README now explaining all the steps required, together with a fully functioning POSTMAN / CURL commands.

Essentially, the problem I believe you had is that you had not added `roles` to your `scope` attribute when creating the JWT Token / authenticating. Take a look at the screenshot below for what you should see (taken from the Sample readme).

![jwtio](https://cloud.githubusercontent.com/assets/2599332/16169744/ece00754-3573-11e6-8169-3420cb1eb556.jpg)

Please let me know if this is still a problem for you. I received your email today too - please ping me via email and if need be I can set up a Zoom session with you and share a screen to ensure your setup is working correctly.  Just ping me if this is needed, even over the weekend. Thanks and best of luck, am hoping the README and sample will make sense.

**Comment by DanailMinchev** [comment]
@arcseldon 

Great! It works!

Thank you for your help!

**Comment by arcseldon** [comment]
@DanailMinchev - great, pleased to hear it. If you do come across any situations where you find you need something and the library could be improved please let me know. Also, there is a configuration value you can set to choose between your JWT being supplied with a ROLES, GROUPS, or SCOPE top level attribute - the default is ROLES (see auth0.authorityStrategy). Thanks.

**Comment by DanailMinchev** [comment]
@arcseldon 

The only thing which is not clear to me is:
`auth0.securedRoute` property in `src/main/resources/auth0.properties`

Probably it is described in the documentation somewhere, but I want to confirm it here.

I can see it is used in `com.auth0.example.AppConfig#authorizeRequests` only.
I actually don't have one common "secure" url pattern.
This means that:
`/api/v1/test1` - should be accessed anonymously like `/ping` in the example
`/api/v1/test2` - should require only authenticated users
`/api/v1/test3` - should require authenticated users + some roles
Also if I understand it correctly the `auth0.securedRoute` property is actually only mandatory for the lib itself (testing), and if I set `auth0.securedRoute` to some default value like `/` and then control all the auth in `com.auth0.example.AppConfig#authorizeRequests` like this:

```
        http.authorizeRequests()
                .antMatchers(HttpMethod.GET, "/api/v1/test1").permitAll()
                .antMatchers(HttpMethod.GET, "/api/v1/test2").authenticated()
                .antMatchers(HttpMethod.GET, "/api/v1/test3").hasAnyAuthority("ROLE_USER", "ROLE_ADMIN");
```

It will work, right?

If it's all correct, could you suggest some default value for `auth0.securedRoute` is it important if it's not used at all in `com.auth0.example.AppConfig#authorizeRequests` ?

**Comment by arcseldon** [comment]
@DanailMinchev - Another excellent observation, thank you for pointing this out. Yes, everything you state above is accurate in so far as `auth0.securedRoute` is concerned.

Have updated our README docs for the library in response to this: [Default Configuration](https://github.com/auth0/auth0-spring-security-api#default-configuration)

Will update the README for the sample too, with a link to that section as this may be something that others also have uncertainty with. That particular setting is a convenience that can safely be ignored if you wish to explicitly just state your own secured routes directly in your own AppConfig.

With regards to your Spring Security `authorizeRequests` settings above, best just quickly test each endpoint and ensure everything works as you expect :)  Just eyeballing it, that looks all good (when in doubt, most specific security settings should come first) - but please just double check by testing the endpoints (remove the JWT token and check you get a 4xx error, alter  your rule to adjust the Role assigned and re-run etc).

Finally, please keep the feedback coming if you notice any other rough edges, you're offering valuable feedback on a library that should gain a great deal of usage v.soon. Best of luck with your project.

**Comment by abobwhite** [comment]
Thanks @arcseldon ! I was having this problem for days and could not figure it out. Was adding `roles` to `scope` documented somewhere? That ended up being my only problem.
