### ISSUE TITLE
SignatureException thrown while decoding JWT token signature verification failed

### ISSUE THREAD

**Issue by bholagabbar** [auth0-samples/auth0-spring-security-api-sample#10]
Hey, So here's the major Issue I am facing. I am using the Authentication sample you provided for my Backend base [https://github.com/auth0-samples/auth0-spring-security-api-sample/tree/master/01-Authentication](https://github.com/auth0-samples/auth0-spring-security-api-sample/tree/master/01-Authentication) and am using the credentials for (clientid, secret etc) from Single Page application i created in the Dashboard.

I have created a separate HTML File with the Auth0 lock that allows me to obtain an `id_token` for my backend. Since it is clearly specified that I can make requests to any of my clients to any of my clients, I believe this token can be anything. Here is the code for the lock:

```
<head>

    <!-- Auth0 lock script -->
    <script src="https://cdn.auth0.com/js/lock/10.9.1/lock.min.js"></script>

    <!-- Setting the right viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>


<button type="submit" id="btn-login">Sign In</button>

<script>
    var lock = new Auth0Lock('cMr82TS37R0DPqLSnC0gCWn2vV3qHK7A', 'wolf-beacon.auth0.com');

    var btn_login = document.getElementById('btn-login');

    btn_login.addEventListener('click', function() {
        lock.show();
    });

    lock.on("authenticated", function(authResult) {
        localStorage.setItem('id_token', authResult.idToken);
    });

</script>

```

After logging in, I simply do `console.log(localStorage.getItem('id_token'))` and get my token from there. After that, I try to make a post request to my backend app using Postman and I keep getting the error `SignatureException thrown while decoding JWT token signature verification failed`. 

![image](https://cloud.githubusercontent.com/assets/11693595/22085949/78349c3a-ddfc-11e6-9e72-6e99cb0dd02f.png) 

I have been trying for 2 days but no luck. Could you please help me out?

**Comment by arcseldon** [comment]
@bholagabbar - so, hitting the `/ping` endpoint works for you, but hitting the `/secured/ping` does not?

If you are getting a signature issue - check your configuration settings:

```
auth0.domain:{DOMAIN}
auth0.issuer:https://{DOMAIN}/
auth0.clientId:{CLIENT_ID}
auth0.clientSecret:{CLIENT_SECRET}
auth0.securedRoute: NOT_USED
auth0.base64EncodedSecret: false
auth0.authorityStrategy: ROLES
auth0.defaultAuth0ApiSecurityEnabled: false
auth0.signingAlgorithm: HS256
#auth0.signingAlgorithm: RS256
#auth0.publicKeyPath: certificate/cert.pem
```

For instance, try toggling `auth0.base64EncodedSecret: false` - is your secret base64 encoded in Dashboard?

Try with `true` and `false`

Did you set issuer correctly ?   is your client using HS256 ?  These are the things you should check. The sample will work out of the box if you have the configuration set correctly.

Double check the Client ID and Secret are correctly configured (no trailing whitespace or accidentally missing a character from end etc).

Make sense?  Let me know how you get on.

**Comment by bholagabbar** [comment]
Hey, none of these seem to be the issue. Is the flow I am following correct? Like getting the token_id from the html form there and then using it to make the post request? I'm really dumbfounded, there's no reason it should not work. Also, my backend is SPA in the dashboard...and I am trying to access it from another SPA client.

**Comment by bholagabbar** [comment]
@arcseldon Hey, there is a file here which shows how to retrieve user details from the older v0 of this library. Here is the link https://github.com/auth0-samples/auth0-spring-security-api-sample/blob/master/02-Authorization/src/main/java/com/auth0/example/Auth0Client.java

I have rewritten it for the new API v1, does it look Ok? We seem to have changed a few classes here and there.


```
package com.wolfbeacon;

import com.auth0.Auth0;
import com.auth0.authentication.AuthenticationAPIClient;
import com.auth0.authentication.result.UserProfile;
import com.auth0.request.Request;
import com.auth0.spring.security.api.authentication.AuthenticationJsonWebToken;

public class Auth0Client {

    private final String clientid;
    private final String domain;
    private final Auth0 auth0;
    private final AuthenticationAPIClient client;

    public Auth0Client(String clientid, String domain) {
        this.clientid = clientid;
        this.domain = domain;
        this.auth0 = new Auth0(clientid, domain);
        this.client = this.auth0.newAuthenticationAPIClient();
    }

    public String getUsername(AuthenticationJsonWebToken token) {
        final Request<UserProfile> request = client.tokenInfo(token.getToken());
        final UserProfile profile = request.execute();
        return profile.getEmail();
    }

}

```

**Comment by gchaturvedi** [comment]
I'm having the exact same issue, none of the java samples work (MVC or spring security).  I filed a ticket already, could someone please help?  I downloaded the sample which contained all the keys already..still the same error as @bholagabbar is seeing above.

**Comment by PraveenRamakrishna** [comment]
@gchaturvedi Even I was hit with same roadblock. Can you please check "auth0-spring-mvc" dependency if its 1.1.2..? which is the case with auth0 java sample projects, please upgrade to 1.2.0. the order version make use of Base64 encoding by default, but now Base64 encoding is disabled for clients by default. Hope this helps

**Comment by jimmyjames** [comment]
Hi @bholagabbar and @gchaturvedi, as this issue is over two years old and this sample and supporting SDKs have changed in that time, I'm going to close this issue. Please don't hesitate to reopen this issue if you are still experiencing these difficulties, and include any updated information (or just open a new ticket). Thanks!
