### ISSUE TITLE
where is the configuration to pull in the auth0.properties?

### ISSUE THREAD

**Issue by eepstein** [auth0-samples/auth0-spring-security-api-sample#11]
Looking at the v1 sample I feel I'm missing something:  where's the config to pull in the auth0.properties ?  In particular the clientId and clientSecret  

To clarify: this is on the V1 branch

(Also, on the master branch now, shouldn't the properties be with '=' between the key and value rather than with ':' or does it not matter whether this is in standard Java .properties format?)

**Comment by lbalmaceda** [comment]
In both `v1` and `master` you must create an Auth0 account and client first. When you do that you get the `domain`, `client_id` and `client_secret` values that you'll then set in the properties file. There's no difference in using `:` or `=` to separate key/values.

**Comment by eepstein** [comment]
Done, thanks.
