### ISSUE TITLE
Link in README 404

### ISSUE THREAD

**Issue by Grimlek** [auth0-samples/auth0-spring-security-api-sample#17]
Please see docs [here](https://auth0.com/docs/api-auth/tutorials/configuring-tenant-for-api-auth) for details.

This section of the README, the link returns a 404. I would do a pull request for it but I have no idea of what it should be. Was just learning the framework.

**Comment by lbalmaceda** [comment]
The readme was outdated. Please refer to this docs https://auth0.com/docs/quickstart/backend/java-spring-security
