### ISSUE TITLE
outdated com.auth0

### ISSUE THREAD

**Issue by vmartynets** [auth0-samples/auth0-spring-security-api-sample#18]
(AUTH-4054)
Sample [use com.auth0 v1.0.0](https://github.com/auth0-samples/auth0-spring-security-api-sample/blob/master/01-Authorization/pom.xml#L51), when up-to-date version is [1.1.0](https://mvnrepository.com/artifact/com.auth0/auth0)

**Comment by lbalmaceda** [comment]
Thanks!
