### ISSUE TITLE
Passing expired token to a public url causes 401

### ISSUE THREAD

**Issue by ryan-walker-kubra** [auth0-samples/auth0-spring-security-api-sample#26]
The following configuration allows unauthenticated access to `/manage/**`. 
However, if you pass an expired  jwt with the request, the response status is `401`. 
I think the jwt should not be checked for public urls.

```
  protected ExpressionUrlAuthorizationConfigurer.ExpressionInterceptUrlRegistry configureHttpSecurity(HttpSecurity http) throws Exception {
    return http
      .authorizeRequests()
      .antMatchers("/manage/**").permitAll()
      .anyRequest().authenticated();
  }
```

**Comment by jimmyjames** [comment]
Hi @ryan-walker-kubra, as this issue is pretty old and the code has changed since reporting, I'm going to close this issue. If you are still experiencing it, don't hesitate to reopen it with any additional information, or create a new issue. Thanks!
