### ISSUE TITLE
Getting error code 401 when calling endpoints /api/private and /api/private-scoped

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-spring-security-api-sample#29]
Getting code 401 for both endpoints `/api/private` and `/api/private-scoped` in the following cases:

A valid token without any scope.
A valid token with a scope of read:messages.
A valid token with a scope of write:messages.
A valid token with the scopes of read:messages and write:messages.

I've tested individually each case using both endpoints and get the desired response.

I was successfully able to get a 401 error with the valid tokens in each case by following this steps:

- Go to the Non interactive clients tab of the API
- Select one of the clients, and display the options.
- Click in the Test button
- When redirected to the Test tab, inmediatly copy the token generated and then go to postman and pasted it.
- Click send just after this.

If the click button is clicked again just after this, the returned code is the expected.

![capture 2018-02-05 at 10 20 41](https://user-images.githubusercontent.com/15818783/36032017-ffaa1184-0d82-11e8-9c7f-11486e4ec4f8.png)

Full display of the errors:
[test.txt](https://github.com/auth0-samples/auth0-spring-security-api-sample/files/1711285/test.txt)

**Comment by alexisluque** [comment]
@paulioceano I test it and worked fine for me. I could reproduce this issue by setting wrong values for `cliente_id` or `audience` parameters. or when `auth0.properties` file doesn't exists.

**Comment by paulioceano** [comment]
@alexisluque I checked and have the values for client_id and audience correctly set.

Also check auth0.properties file.

Still having the same issue

**Comment by loket** [comment]
I had the same problem. It seems Postman includes the `access_token` and not the `id_token` as part of the request (assuming you've set up your collection to use OAuth 2.0): [link](https://stackoverflow.com/a/42361093/6730769)

Adding this part to my `application.properties` helped me identify the problem:

```java
logging.level.com.auth0.spring.security.api=DEBUG
```

Instead of just getting an `AccessDeniedException`, I got this (very helpful) error message:

```bash
2018-09-27 11:10:27.713 DEBUG 85860 --- [nio-3010-exec-2] c.a.s.s.api.JwtAuthenticationProvider    : Failed to decode token as jwt

com.auth0.jwt.exceptions.JWTDecodeException: The token was expected to have 3 parts, but got 1.
	at com.auth0.jwt.TokenUtils.splitToken(TokenUtils.java:21) ~[java-jwt-3.2.0.jar:na]
	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:27) ~[java-jwt-3.2.0.jar:na]
	at com.auth0.jwt.JWT.decode(JWT.java:21) ~[java-jwt-3.2.0.jar:na]
	at com.auth0.spring.security.api.authentication.PreAuthenticatedAuthenticationJsonWebToken.usingToken(PreAuthenticatedAuthenticationJsonWebToken.java:68) ~[auth0-spring-security-api-1.0.0-rc.3.jar:na]
	at com.auth0.spring.security.api.BearerSecurityContextRepository.loadContext(BearerSecurityContextRepository.java:22) [auth0-spring-security-api-1.0.0-rc.3.jar:na]
...
```

Honestly, I think this should be logged as `WARNING` or `ERROR` instead of `DEBUG`.

Ensuring the token is [valid](https://jwt.io/) should increase chances of success. 😃 Any chance your issue is/was the same as mine?

**Comment by jimmyjames** [comment]
Hi @paulioceano, as this issue is more than a year old and there is good info above from @loket, I'm going to close it in one week unless you are still having this issue. If you are still experiencing it just comment here and we can try to work through what's going on. Thanks!
