### ISSUE TITLE
x-xsrf-token is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by gwooding** [auth0-samples/auth0-spring-security-api-sample#8]
I've been trying to run this example with the Auth0 Angular 2 08 project here:

https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/tree/master/08-Calling-Api

And I'm getting this error whenever I press either Ping button:

XMLHttpRequest cannot load http://localhost:3001/ping. Request header field x-xsrf-token is not allowed by Access-Control-Allow-Headers in preflight response.
ping:1 XMLHttpRequest cannot load http://localhost:3001/secured/ping. Request header field x-xsrf-token is not allowed by Access-Control-Allow-Headers in preflight response.

The problem seems to be that the response headers from the server need to have this header added to them:

"Access-Control-Allow-Headers", "x-xsrf-token".

I've tried many different ideas and cannot get it to work.

**Comment by arcseldon** [comment]
@gwooding - please can you attach a HAR file with the request and response. 

See [here](https://auth0.com/docs/tutorials/troubleshootings-with-har-files) for details if you are unfamiliar with troubleshooting with HAR files.

With that I can take a look at what is going on, and offer a solution.

**Comment by arcseldon** [comment]
@gwooding - feel free to override [this class](https://github.com/auth0/auth0-spring-security-api/blob/master/src/main/java/com/auth0/spring/security/api/Auth0CORSFilter.java) and test alternate CORS settings too.

**Comment by gwooding** [comment]
Hi, 
Thanks for the help.  Firstly, here's the repo with attempts at solving it myself commented out, I'm not sure if any of them will be of use to you. 

[https://github.com/gwooding/Auth0SpringTraining/blob/master/src/main/java/com/auth0/example/AppConfig.java]

 I did try creating my own filter as well as several other ideas, but with no success.  If you could help me I'd be very grateful.  I think the solution would be very useful to other Auth0 users. 

Please find the files attached that you requested.  Running the public "Ping" in Incognito worked fine, however the secure "Ping" created a 401, but did not print the error to the console.  It was only in regular chrome where I would see the error mentioned above. 

[Archive.zip](https://github.com/auth0-samples/auth0-spring-security-api-sample/files/546680/Archive.zip)

**Comment by arcseldon** [comment]
@gwooding - taken a look. Locally i can append the header with no issues. Also, in your HAR, for the failed secured endpoint you are not supplying the header in question.  Your problem is likely related to your [config file](https://github.com/gwooding/Auth0SpringTraining/blob/master/src/main/resources/auth0.properties) - the values for clientId and clientSecret look wrong.

**Comment by gwooding** [comment]
Ahh could you send me the code you used to append, so I can rule that out?

The front end works fine with an express.js API so I don't think it's that.  The HAR for regular chrome definitely has the right header, not sure why.  I'll double check the secret and ID too.

**Comment by arcseldon** [comment]
@gwooding - in the HAR file you sent the 401 request did not appear to contain the header you mention above.  I checked your dashboard, and setup `API` for you - you will see this as a new entry on the side nav bar beneath Clients. This is how you should be defining an API.

i setup a local application that runs against your tenant and was successfully authenticating against the `secured/ping` endpoint. Here is a working config -- grab your secret from `API -> TestApi -> Settings`

```
auth0.domain: gwooding.eu.auth0.com
auth0.issuer: https://gwooding.eu.auth0.com/
auth0.clientId: https://gwooding.myapi.com
auth0.clientSecret: XXX  // signing secret of TestApi 
auth0.securedRoute: NOT_USED
auth0.base64EncodedSecret: false
auth0.authorityStrategy: SCOPE
auth0.defaultAuth0ApiSecurityEnabled: false
auth0.signingAlgorithm: HS256
```

FYI only - if you still have problems - you can simply use the `auth0.defaultAuth0ApiSecurityEnabled` property and set this to `true` if you want to disable the default configuration file for the library. Then,  just copy and paste the [original](https://github.com/auth0/auth0-spring-security-api/blob/b7893edbbbbe908543af85cbfa3fca4c9d356319/src/main/java/com/auth0/spring/security/api/Auth0SecurityConfig.java) just changing the parts you need.  This ensures you are not accidentally pulling in the original CORS Filter etc.  Make sense?
